-- 公司配置表
DROP TABLE IF EXISTS `bmp_basic_system_company`;
CREATE TABLE `bmp_basic_system_company` (
                                            `id` VARCHAR(100) NOT NULL COMMENT 'ID',
                                            `create_date` DATETIME DEFAULT NULL COMMENT '创建时间',
                                            `create_by` VARCHAR(100) DEFAULT NULL COMMENT '创建人',
                                            `update_date` DATETIME DEFAULT NULL COMMENT '更新时间',
                                            `update_by` VARCHAR(100) DEFAULT NULL COMMENT '更新人',
                                            `disable` INT DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                            `del_flag` INT DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                            `company_id` VARCHAR(100) NOT NULL COMMENT '公司ID',
                                            `name` VARCHAR(100) DEFAULT NULL COMMENT '公司名称',
                                            `appid` VARCHAR(100) DEFAULT NULL COMMENT 'appid',
                                            `aeskey` VARCHAR(100) DEFAULT NULL COMMENT 'aeskey',
                                            `token` VARCHAR(100) DEFAULT NULL COMMENT 'token',
                                            `server_url` VARCHAR(100) DEFAULT NULL COMMENT '服务端地址',
                                            `visitor_url` VARCHAR(100) DEFAULT NULL COMMENT '访客端地址',
                                            `api_url` VARCHAR(100) DEFAULT NULL COMMENT '服务器接口地址',
                                            `log_data` INT NOT NULL DEFAULT '7' COMMENT '日志保留天数',
                                            PRIMARY KEY (`id`),
                                            UNIQUE KEY `keyx_company_id` (`company_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='公司配置';

-- 通用层级元素表
DROP TABLE IF EXISTS `bmp_base_common_element`;
CREATE TABLE `bmp_base_common_element` (
                                           `id` VARCHAR(100) NOT NULL COMMENT 'ID',
                                           `create_date` DATETIME DEFAULT NULL COMMENT '创建时间',
                                           `create_by` VARCHAR(100) DEFAULT NULL COMMENT '创建人',
                                           `update_date` DATETIME DEFAULT NULL COMMENT '更新时间',
                                           `update_by` VARCHAR(100) DEFAULT NULL COMMENT '更新人',
                                           `disable` INT DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                           `del_flag` INT DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                           `company_id` VARCHAR(100) DEFAULT NULL COMMENT '公司ID',
                                           `name` VARCHAR(100) DEFAULT NULL COMMENT '元素名称',
                                           `parent_id` VARCHAR(100) DEFAULT NULL COMMENT '父级ID',
                                           `order_no` int DEFAULT NULL COMMENT '排序',
                                           `top_id` VARCHAR(100) DEFAULT NULL COMMENT '顶级ID',
                                           `biz_id` VARCHAR(100) DEFAULT NULL COMMENT '业务关联ID',
                                           `biz_type` VARCHAR(100) NOT NULL COMMENT '业务类型',
                                           `biz_content` text DEFAULT NULL COMMENT '业务数据',
                                           PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='通用层级元素表';

-- 系统附件表
DROP TABLE IF EXISTS `bmp_base_system_file`;
CREATE TABLE `bmp_base_system_file` (
                                        `id` varchar(100) NOT NULL COMMENT 'ID',
                                        `create_date` datetime NOT NULL COMMENT '创建时间',
                                        `create_by` varchar(100) DEFAULT NULL COMMENT '创建人',
                                        `update_date` datetime DEFAULT NULL COMMENT '更新时间',
                                        `update_by` varchar(100) DEFAULT NULL COMMENT '更新人',
                                        `disable` int DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                        `del_flag` int DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                        `file_name` varchar(100) NOT NULL COMMENT '文件名',
                                        `file_ext` varchar(100) NOT NULL COMMENT '文件后缀名',
                                        `biz_id` varchar(100) DEFAULT NULL COMMENT '绑定的业务id',
                                        `file_size` bigint NOT NULL COMMENT '文件大小',
                                        `real_path` varchar(500) DEFAULT NULL COMMENT '绝对路径',
                                        `biz_name` varchar(100) DEFAULT NULL COMMENT '业务名称。表名',
                                        PRIMARY KEY (`id`),
                                        KEY `keyx_biz_id` (`biz_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='系统附件表';

-- 系统配置表
DROP TABLE IF EXISTS `bmp_base_system_base_config`;
CREATE TABLE `bmp_base_system_base_config` (
                                               `id` varchar(100) NOT NULL COMMENT 'ID',
                                               `create_date` datetime NOT NULL COMMENT '创建时间',
                                               `create_by` varchar(100) DEFAULT NULL COMMENT '创建人',
                                               `update_date` datetime DEFAULT NULL COMMENT '更新时间',
                                               `update_by` varchar(100) DEFAULT NULL COMMENT '更新人',
                                               `disable` int DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                               `del_flag` int DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                               `data_name` varchar(100) DEFAULT NULL COMMENT '名称',
                                               `data_value` varchar(500) DEFAULT NULL COMMENT '值',
                                               `data_type` varchar(50) DEFAULT NULL COMMENT '参数类型',
                                               `main_code` varchar(20) DEFAULT NULL COMMENT '主类型',
                                               `sub_code` varchar(20) DEFAULT NULL COMMENT '辅类型',
                                               `remarks` varchar(100) DEFAULT NULL COMMENT '备注',
                                               `content` mediumtext COMMENT '内容',
                                               PRIMARY KEY (`id`) USING BTREE,
                                               UNIQUE KEY `system_base_config_data_name` (`data_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='系统配置表';

-- 服务器交互日志
DROP TABLE IF EXISTS `bmp_server_api_log`;
CREATE TABLE `bmp_server_api_log` (
                                      `msg_id` varchar(100) NOT NULL COMMENT '消息ID，服务器交互数据消息唯一id',
                                      `company_id` varchar(100) NOT NULL COMMENT '公司ID',
                                      `timestamp` bigint NOT NULL COMMENT '请求时间戳',
                                      `data_type` varchar(100) NOT NULL COMMENT '事件类型',
                                      `url` varchar(500) NOT NULL COMMENT '请求路径',
                                      `method` varchar(100) NOT NULL COMMENT '请求方法',
                                      `ciphertext` text NOT NULL COMMENT '密文',
                                      `plaintext` text NOT NULL COMMENT '明文',
                                      `post_time` bigint NOT NULL COMMENT '服务器接收POST数据时间',
                                      `debug` text DEFAULT NULL COMMENT '请求参数',
                                      PRIMARY KEY (`msg_id`),
                                      KEY `keyx_company_id` (`company_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='服务器交互日志';

-- 公司状态
DROP TABLE IF EXISTS `bmp_server_company_status`;
CREATE TABLE `bmp_server_company_status` (
                                             `id` varchar(100) NOT NULL COMMENT '唯一ID',
                                             `create_date` datetime DEFAULT NULL COMMENT '创建时间',
                                             `create_by` varchar(100) DEFAULT NULL COMMENT '创建触发事件',
                                             `update_date` datetime DEFAULT NULL COMMENT '更新时间',
                                             `update_by` varchar(100) DEFAULT NULL COMMENT '更新触发事件',
                                             `disable` INT DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                             `del_flag` INT DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                             `company_id` varchar(100) NOT NULL COMMENT '公司ID',
                                             `company_status` int NOT NULL COMMENT '公司状态。1：在线，2：离线',
                                             PRIMARY KEY (`id`),
                                             KEY `keyx_company_id` (`company_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='公司状态';

-- 路由状态
DROP TABLE IF EXISTS `bmp_server_route_status`;
CREATE TABLE `bmp_server_route_status` (
                                           `id` varchar(100) NOT NULL COMMENT '唯一ID',
                                           `create_date` datetime DEFAULT NULL COMMENT '创建时间',
                                           `create_by` varchar(100) DEFAULT NULL COMMENT '创建触发事件',
                                           `update_date` datetime DEFAULT NULL COMMENT '更新时间',
                                           `update_by` varchar(100) DEFAULT NULL COMMENT '更新触发事件',
                                           `disable` INT DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                           `del_flag` INT DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                           `company_id` varchar(100) NOT NULL COMMENT '公司ID',
                                           `route_status` int NOT NULL COMMENT '路由状态。1：在线，2：离线',
                                           `route_id` bigint NOT NULL COMMENT '路由ID',
                                           `route_name` varchar(100) NOT NULL COMMENT '路由名称',
                                           PRIMARY KEY (`id`),
                                           KEY `keyx_company_id` (`company_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='路由状态';

-- 接待组状态
DROP TABLE IF EXISTS `bmp_server_skill_status`;
CREATE TABLE `bmp_server_skill_status` (
                                           `id` varchar(100) NOT NULL COMMENT '唯一ID',
                                           `create_date` datetime DEFAULT NULL COMMENT '创建时间',
                                           `create_by` varchar(100) DEFAULT NULL COMMENT '创建触发事件',
                                           `update_date` datetime DEFAULT NULL COMMENT '更新时间',
                                           `update_by` varchar(100) DEFAULT NULL COMMENT '更新触发事件',
                                           `disable` INT DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                           `del_flag` INT DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                           `company_id` varchar(100) NOT NULL COMMENT '公司ID',
                                           `skill_status` int NOT NULL COMMENT '接待组状态。1：在线，2：离线',
                                           `skill_id` bigint NOT NULL COMMENT '接待组ID',
                                           `skill_name` varchar(100) NOT NULL COMMENT '接待组名称',
                                           PRIMARY KEY (`id`),
                                           KEY `keyx_company_id` (`company_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='接待组状态';

-- 客服状态
DROP TABLE IF EXISTS `bmp_server_staff_status`;
CREATE TABLE `bmp_server_staff_status` (
                                           `id` varchar(100) NOT NULL COMMENT '唯一ID',
                                           `create_date` datetime DEFAULT NULL COMMENT '创建时间',
                                           `create_by` varchar(100) DEFAULT NULL COMMENT '创建触发事件',
                                           `update_date` datetime DEFAULT NULL COMMENT '更新时间',
                                           `update_by` varchar(100) DEFAULT NULL COMMENT '更新触发事件',
                                           `disable` INT DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                           `del_flag` INT DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                           `company_id` varchar(100) NOT NULL COMMENT '公司ID',
                                           `staff_status` int NOT NULL COMMENT '客服状态。1：在线，2：忙碌，3：离开，4：隐身，5：退出',
                                           `staff_id` bigint NOT NULL COMMENT '客服ID',
                                           `staff_logname` varchar(100) NOT NULL COMMENT '客服登陆账号',
                                           `staff_name` varchar(100) NOT NULL COMMENT '客服姓名',
                                           PRIMARY KEY (`id`),
                                           KEY `keyx_company_id` (`company_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='客服状态';

-- 对话数据
DROP TABLE IF EXISTS `bmp_server_chat_record`;
CREATE TABLE `bmp_server_chat_record` (
                                          `id` varchar(100) NOT NULL COMMENT '唯一ID',
                                          `create_date` datetime DEFAULT NULL COMMENT '创建时间',
                                          `create_by` varchar(100) DEFAULT NULL COMMENT '创建触发事件',
                                          `update_date` datetime DEFAULT NULL COMMENT '更新时间',
                                          `update_by` varchar(100) DEFAULT NULL COMMENT '更新触发事件',
                                          `disable` INT DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                          `del_flag` INT DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                          `company_id` varchar(100) NOT NULL COMMENT '公司ID',
                                          `chat_record_type` int DEFAULT NULL COMMENT '对话记录类型。1：人工对话 2：机器人对话 3：留言 4：推送',
                                          `my_data` text COMMENT '开发者自定义扩展数据',
                                          `chat_status` int DEFAULT NULL COMMENT '对话状态。1：人工对话开始，2：人工对话结束，3：留言开始，4：留言结束，5：机器人对话开始，6：机器人对话结束',
                                          `is_transfer` int DEFAULT NULL COMMENT '对话是否存在转接。0：无转接，1：有转接',
                                          `uid` varchar(100) DEFAULT NULL COMMENT '会员唯一值',
                                          `grade` int DEFAULT NULL COMMENT '会员级别。大于“0”的数字',
                                          `category` varchar(100) DEFAULT NULL COMMENT '会员类别',
                                          `name` varchar(100) DEFAULT NULL COMMENT '会员姓名',
                                          `nick_name` varchar(100) DEFAULT NULL COMMENT '会员昵称',
                                          `gender` int DEFAULT NULL COMMENT '会员性别。0：未知，1：男，2：女',
                                          `age` varchar(100) DEFAULT NULL COMMENT '会员年龄',
                                          `birthday` varchar(100) DEFAULT NULL COMMENT '会员生日',
                                          `marital_status` int DEFAULT NULL COMMENT '会员婚姻状况。0：未知，1：未婚，2：已婚',
                                          `phone` varchar(100) DEFAULT NULL COMMENT '会员联系电话',
                                          `qq` varchar(100) DEFAULT NULL COMMENT '会员QQ',
                                          `wechat` varchar(100) DEFAULT NULL COMMENT '会员微信',
                                          `email` varchar(100) DEFAULT NULL COMMENT '会员邮箱',
                                          `nation` varchar(100) DEFAULT NULL COMMENT '会员国家',
                                          `province` varchar(100) DEFAULT NULL COMMENT '会员省份',
                                          `city` varchar(100) DEFAULT NULL COMMENT '会员城市',
                                          `address` varchar(500) DEFAULT NULL COMMENT '会员地址',
                                          `photo` varchar(500) DEFAULT NULL COMMENT '会员头像地址',
                                          `memo` varchar(100) DEFAULT NULL COMMENT '会员备注信息',
                                          `c1` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c2` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c3` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c4` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c5` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c6` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c7` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c8` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c9` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c10` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c11` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c12` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c13` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c14` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c15` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c16` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c17` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c18` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c19` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `c20` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                          `visitor_enter_time` datetime DEFAULT NULL COMMENT '访客进入网站的时间',
                                          `visitor_media` int DEFAULT NULL COMMENT '访客端的媒介。1：电脑端网页，2：移动端网页，5：微信，6：Android SDK，9：自定义渠道，11：邮箱渠',
                                          `visitor_type` int DEFAULT NULL COMMENT '访客类型。-1：未知，0：游客，1：会员，4：微信公众号渠道，5：自定义渠道，8：邮箱渠道',
                                          `media_id` varchar(100) DEFAULT NULL COMMENT '自定义渠道的渠道ID',
                                          `visitor_id` varchar(100) DEFAULT NULL COMMENT '访客ID',
                                          `visitor_name` varchar(100) DEFAULT NULL COMMENT '访客的姓名',
                                          `visitor_photo` varchar(500) DEFAULT NULL COMMENT '访客的头像地址',
                                          `visit_times` int DEFAULT NULL COMMENT '访客的来访次数',
                                          `visitor_lan` varchar(100) DEFAULT NULL COMMENT '访客的浏览器语言',
                                          `visitor_ip` varchar(100) DEFAULT NULL COMMENT '访客的来源IP',
                                          `visitor_country` varchar(100) DEFAULT NULL COMMENT '访客的来源国家',
                                          `visitor_province` varchar(100) DEFAULT NULL COMMENT '访客的来源省份',
                                          `visitor_city` varchar(100) DEFAULT NULL COMMENT '访客的来源城市',
                                          `browser_name` varchar(100) DEFAULT NULL COMMENT '访客的浏览器名称',
                                          `browser_version` varchar(100) DEFAULT NULL COMMENT '访客的浏览器版本号',
                                          `screen_resolution` varchar(100) DEFAULT NULL COMMENT '访客电脑的分辨率',
                                          `os_name` varchar(100) DEFAULT NULL COMMENT '访客电脑的操作系统',
                                          `os_version` varchar(100) DEFAULT NULL COMMENT '访客电脑的操作系统版本',
                                          `se` varchar(100) DEFAULT NULL COMMENT '访客来源的搜索引擎',
                                          `keyword` varchar(100) DEFAULT NULL COMMENT '访客来源的关键词',
                                          `bidding_word` varchar(100) DEFAULT NULL COMMENT '推广',
                                          `keyword_type` int DEFAULT NULL COMMENT '关键字类型。0：未区分SEO、推广，1：自然优化，2：付费推广',
                                          `refer_page` text COMMENT '访客进入网站的来源页',
                                          `first_time` datetime DEFAULT NULL COMMENT '进入网站的时间',
                                          `first_page` text COMMENT '访客落地页面的URL',
                                          `first_page_title` varchar(100) DEFAULT NULL COMMENT '访客落地页面的标题',
                                          `first_page_alias` varchar(100) DEFAULT NULL COMMENT '访客落地页面的别名',
                                          `last_chat_time` datetime DEFAULT NULL COMMENT '上次对话的时间',
                                          `last_chat_staff_id` bigint DEFAULT NULL COMMENT '上次对话的客服ID',
                                          `last_chat_staff_logname` varchar(100) DEFAULT NULL COMMENT '上次对话的客服账号',
                                          `last_chat_staff_name` varchar(100) DEFAULT NULL COMMENT '上次对话的客服姓名',
                                          `route_id` bigint DEFAULT NULL COMMENT '接入对话的路由ID。-1：web访客的默认路由，-2：微信公众号对话的默认路由，-3：SDK对话的默认路由，-7：自定义渠道的默认路由',
                                          `route_name` varchar(100) DEFAULT NULL COMMENT '路由名称',
                                          `style_id` bigint DEFAULT NULL COMMENT '路由所使用的样式ID',
                                          `style_name` varchar(100) DEFAULT NULL COMMENT '路由所使用样式的名称',
                                          `route_chat_department_id` bigint DEFAULT NULL COMMENT '本次分配对话的接待组ID。0：全部人员可接待',
                                          `route_chat_department_name` varchar(100) DEFAULT NULL COMMENT '本地分配对话的接待组名称',
                                          `chat_page` varchar(100) DEFAULT NULL COMMENT '对话页面',
                                          `chat_page_title` varchar(100) DEFAULT NULL COMMENT '对话页面标题',
                                          `chat_times` int DEFAULT NULL COMMENT '访客的对话次数',
                                          `chat_event` int DEFAULT NULL COMMENT '对话发起的方式。1：点击图标，2：接受邀请对话，3：客服主动对话，4：微信输入任意文字接入对话，5：微信点击菜单接入，6：微信输入指定文字接入，7：微信机器人转人工，11：机器人转人工，12：机器人转留言，14：web自动弹屏自动接入，15：web自动弹屏访客输入消息接入，16：商户留言转平台接入，17：微信开发者接入，18：自定义渠道事件接入，19：自定义渠道发送消息接入，21：微信指定路由接入，26：邮箱渠道发送留言接入',
                                          `chat_request_time` datetime DEFAULT NULL COMMENT '请求对话的时间',
                                          `chat_answer_time` datetime DEFAULT NULL COMMENT '对话接通的时间',
                                          `chat_type` int DEFAULT NULL COMMENT '会话类型。1：在线对话，2：忙碌对话，3：离线消息，5：机器人对话',
                                          `chat_staff_id` bigint DEFAULT NULL COMMENT '接待对话的客服ID',
                                          `chat_staff_logname` varchar(100) DEFAULT NULL COMMENT '接待对话的客服账号',
                                          `chat_staff_name` varchar(100) DEFAULT NULL COMMENT '接待对话的客服姓名',
                                          `chat_staff_role` varchar(100) DEFAULT NULL COMMENT '接待对话的客服的内部角色名称',
                                          `chat_entrance` varchar(100) DEFAULT NULL COMMENT '对话入口',
                                          `chat_record_id` varchar(100) DEFAULT NULL COMMENT '对话记录的ID',
                                          `chat_wait_time` bigint DEFAULT NULL COMMENT '访客等待时长。单位：毫秒',
                                          `chat_department_id` bigint DEFAULT NULL COMMENT '本次分配对话的分组ID。0：全部人员可接',
                                          `chat_department_name` varchar(100) DEFAULT NULL COMMENT '本次分配对话的分组名',
                                          `chat_score` int DEFAULT NULL COMMENT '满意度评价。1：非常不满意，2：不满意，3：一般，4：满意，5：非常满',
                                          `score_dimension` varchar(100) DEFAULT NULL COMMENT '评价维度',
                                          `score_suggest` varchar(100) DEFAULT NULL COMMENT '评价的内容',
                                          `score_chat_staff_id` varchar(100) DEFAULT NULL COMMENT '评价发生时，正在接待对话的客服ID',
                                          `score_chat_staff_logname` varchar(100) DEFAULT NULL COMMENT '评价发生时，正在接待对话的客服账号',
                                          `score_chat_staff_name` varchar(100) DEFAULT NULL COMMENT '评价发生时，正在接待对话的客服姓名',
                                          `chat_subject` varchar(100) DEFAULT NULL COMMENT '对话评估主题',
                                          `chat_subject_memo` varchar(100) DEFAULT NULL COMMENT '对话评估备注',
                                          `chat_end_time` datetime DEFAULT NULL COMMENT '对话结束时间',
                                          `chat_end_type` int DEFAULT NULL COMMENT '对话结束方式。0：未知，1：访客结束对话，2：客服结束对话，3：访客超时，5：客服退出，6：系统关闭，8：访客长时间未回复结束，12：忙碌放弃结束，14：留言超时结束，15：机器人自动转人工结束，16：机器人手动转人工结束，18：客服主动对话后留言/机器人对话结束，19：机器人超时结束',
                                          `chat_total_time` bigint DEFAULT NULL COMMENT '通话时长。单位：毫秒',
                                          `first_answer_time` bigint DEFAULT NULL COMMENT '首次响应时长。单位：毫秒',
                                          `avg_answer_time` bigint DEFAULT NULL COMMENT '平均响应时长。单位：毫秒',
                                          `visitor_send_msg` int DEFAULT NULL COMMENT '访客发送消息条数',
                                          `staff_send_msg` int DEFAULT NULL COMMENT '客服发送消息条数',
                                          `activelyInvite_evaluating` int DEFAULT NULL COMMENT '是否邀评。0：没有邀评，1：有邀评',
                                          `chat_content` text COMMENT '对话内容',
                                          `staff_id` bigint DEFAULT NULL COMMENT '客服ID',
                                          `staff_logname` varchar(100) DEFAULT NULL COMMENT '客服账',
                                          `staff_name` varchar(100) DEFAULT NULL COMMENT '客服姓',
                                          `owner_id` bigint DEFAULT NULL COMMENT '所有者ID',
                                          `owner_logname` varchar(100) DEFAULT NULL COMMENT '所有者账号',
                                          `owner_name` varchar(100) DEFAULT NULL COMMENT '所有者姓名',
                                          `perfect_matchs` int DEFAULT NULL COMMENT '完全匹配数',
                                          `exact_matchs` int DEFAULT NULL COMMENT '精准匹配数',
                                          `similarity_matchs` int DEFAULT NULL COMMENT '相似匹配数',
                                          `mis_match_count` int DEFAULT NULL COMMENT '未命中数',
                                          `solved_count` int DEFAULT NULL COMMENT '点击解决数',
                                          `unsolved_count` int DEFAULT NULL COMMENT '点击未解决数',
                                          PRIMARY KEY (`id`),
                                          UNIQUE KEY `unique_keys_chat_record_id` (`chat_record_id`) USING BTREE,
                                          KEY `keyx_company_id` (`company_id`) USING BTREE,
                                          KEY `keyx_visitor_id` (`visitor_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='对话数据';

-- 客服Kpi数据
DROP TABLE IF EXISTS `bmp_server_chat_record_staff_kpi`;
CREATE TABLE `bmp_server_chat_record_staff_kpi` (
                                                    `id` varchar(100) NOT NULL COMMENT '唯一ID',
                                                    `create_date` datetime DEFAULT NULL COMMENT '创建时间',
                                                    `create_by` varchar(100) DEFAULT NULL COMMENT '创建触发事件',
                                                    `update_date` datetime DEFAULT NULL COMMENT '更新时间',
                                                    `update_by` varchar(100) DEFAULT NULL COMMENT '更新触发事件',
                                                    `disable` INT DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                                    `del_flag` INT DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                                    `company_id` varchar(100) NOT NULL COMMENT '公司ID',
                                                    `staff_id` varchar(100) DEFAULT NULL COMMENT '客服ID',
                                                    `staff_logname` varchar(100) DEFAULT NULL COMMENT '客服账号',
                                                    `staff_name` varchar(100) DEFAULT NULL COMMENT '客服姓名',
                                                    `first_answer_time` int DEFAULT NULL COMMENT '首次响应时长。单位：秒',
                                                    `avg_answer_time` int DEFAULT NULL COMMENT '平均响应时长。单位：秒',
                                                    `visitor_send_msg` int DEFAULT NULL COMMENT '访客发送消息条数',
                                                    `staff_send_msg` int DEFAULT NULL COMMENT '客服发送消息条数',
                                                    `duration` int DEFAULT NULL COMMENT '总通话时长。单位：秒',
                                                    `chat_record_id` varchar(100) NOT NULL COMMENT '对话记录ID',
                                                    PRIMARY KEY (`id`),
                                                    KEY `keyx_chat_record_id` (`chat_record_id`) USING BTREE,
                                                    KEY `keyx_company_id` (`company_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='客服Kpi数据';

-- 对话转接
DROP TABLE IF EXISTS `bmp_server_chat_record_transfer`;
CREATE TABLE `bmp_server_chat_record_transfer` (
                                                   `id` varchar(100) NOT NULL COMMENT '唯一ID',
                                                   `create_date` datetime DEFAULT NULL COMMENT '创建时间',
                                                   `create_by` varchar(100) DEFAULT NULL COMMENT '创建触发事件',
                                                   `update_date` datetime DEFAULT NULL COMMENT '更新时间',
                                                   `update_by` varchar(100) DEFAULT NULL COMMENT '更新触发事件',
                                                   `disable` INT DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                                   `del_flag` INT DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                                   `company_id` varchar(100) NOT NULL COMMENT '公司ID',
                                                   `chat_record_id` varchar(100) DEFAULT NULL COMMENT '对话记录ID',
                                                   `transfer_time` datetime DEFAULT NULL COMMENT '转接时间',
                                                   `from_staff_id` varchar(100) DEFAULT NULL COMMENT '发起转接的客服ID',
                                                   `from_staff_logname` varchar(100) DEFAULT NULL COMMENT '发起转接的客服账号',
                                                   `from_staff_name` varchar(100) DEFAULT NULL COMMENT '发起转接的客服姓名',
                                                   `to_staff_id` varchar(100) DEFAULT NULL COMMENT '接受转接的客服ID',
                                                   `to_staff_logname` varchar(100) DEFAULT NULL COMMENT '接受转接的客服账号',
                                                   `to_staff_name` varchar(100) DEFAULT NULL COMMENT '接受转接的客服姓名',
                                                   PRIMARY KEY (`id`),
                                                   KEY `keyx_chat_record_id` (`chat_record_id`) USING BTREE,
                                                   KEY `keyx_company_id` (`company_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='对话转接';

-- 浏览数据
DROP TABLE IF EXISTS `bmp_server_track_record`;
CREATE TABLE `bmp_server_track_record` (
                                           `id` varchar(100) NOT NULL COMMENT '唯一ID',
                                           `create_date` datetime DEFAULT NULL COMMENT '创建时间',
                                           `create_by` varchar(100) DEFAULT NULL COMMENT '创建触发事件',
                                           `update_date` datetime DEFAULT NULL COMMENT '更新时间',
                                           `update_by` varchar(100) DEFAULT NULL COMMENT '更新触发事件',
                                           `disable` INT DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                           `del_flag` INT DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                           `company_id` varchar(100) NOT NULL COMMENT '公司ID',
                                           `my_data` text COMMENT '开发者自定义扩展数据',
                                           `enter_route_status` int DEFAULT NULL COMMENT '访客进入时的路由状态。1：在线，2：离线',
                                           `out_route_status` int DEFAULT NULL COMMENT '访客退出时的路由状态。1：在线，2：离线',
                                           `uid` varchar(100) DEFAULT NULL COMMENT '会员唯一值',
                                           `grade` int DEFAULT NULL COMMENT '会员级别。大于0的数字',
                                           `category` varchar(100) DEFAULT NULL COMMENT '会员类别',
                                           `name` varchar(100) DEFAULT NULL COMMENT '会员姓名',
                                           `nick_name` varchar(100) DEFAULT NULL COMMENT '会员昵称',
                                           `gender` int DEFAULT NULL COMMENT '会员性别。0：未知，1：男，2：女',
                                           `age` varchar(100) DEFAULT NULL COMMENT '会员年龄',
                                           `birthday` varchar(100) DEFAULT NULL COMMENT '会员生日',
                                           `marital_status` int DEFAULT NULL COMMENT '会员婚姻状况。0：未知，1：未婚，2：已婚',
                                           `phone` varchar(100) DEFAULT NULL COMMENT '会员联系电话',
                                           `qq` varchar(100) DEFAULT NULL COMMENT '会员QQ',
                                           `wechat` varchar(100) DEFAULT NULL COMMENT '会员微信',
                                           `email` varchar(100) DEFAULT NULL COMMENT '会员邮箱',
                                           `nation` varchar(100) DEFAULT NULL COMMENT '会员国家',
                                           `province` varchar(100) DEFAULT NULL COMMENT '会员省份',
                                           `city` varchar(100) DEFAULT NULL COMMENT '会员城市',
                                           `address` varchar(500) DEFAULT NULL COMMENT '会员地址',
                                           `photo` varchar(500) DEFAULT NULL COMMENT '会员头像地址',
                                           `memo` varchar(100) DEFAULT NULL COMMENT '会员备注信息',
                                           `visitor_enter_time` datetime DEFAULT NULL COMMENT '访客进入网站的时间',
                                           `visitor_media` int DEFAULT NULL COMMENT '访客端的媒介。1：电脑端网页，2：移动端网页',
                                           `visitor_type` int DEFAULT NULL COMMENT '访客类型。-1：未知，0：游客，1：会员',
                                           `media_id` varchar(100) DEFAULT NULL COMMENT '自定义渠道的渠道ID',
                                           `visitor_id` varchar(100) DEFAULT NULL COMMENT '访客ID',
                                           `visitor_name` varchar(100) DEFAULT NULL COMMENT '访客的姓名',
                                           `visitor_photo` varchar(500) DEFAULT NULL COMMENT '访客的头像地址',
                                           `visit_times` int DEFAULT NULL COMMENT '当前访客此次是第几次来访',
                                           `visitor_lan` varchar(100) DEFAULT NULL COMMENT '访客的浏览器语言',
                                           `visitor_ip` varchar(100) DEFAULT NULL COMMENT '访客的来源IP',
                                           `visitor_country` varchar(100) DEFAULT NULL COMMENT '访客的来源国家',
                                           `visitor_province` varchar(100) DEFAULT NULL COMMENT '访客的来源省份',
                                           `visitor_city` varchar(100) DEFAULT NULL COMMENT '访客的来源城市',
                                           `browser_name` varchar(100) DEFAULT NULL COMMENT '访客的浏览器名称',
                                           `browser_version` varchar(100) DEFAULT NULL COMMENT '访客的浏览器版本号',
                                           `screen_resolution` varchar(100) DEFAULT NULL COMMENT '访客电脑的分辨率',
                                           `os_name` varchar(100) DEFAULT NULL COMMENT '访客电脑的操作系统',
                                           `os_version` varchar(100) DEFAULT NULL COMMENT '访客电脑的操作系统版本',
                                           `se` varchar(100) DEFAULT NULL COMMENT '访客来源的搜索引擎',
                                           `keyword` varchar(100) DEFAULT NULL COMMENT '访客来源的关键词',
                                           `bidding_word` varchar(100) DEFAULT NULL COMMENT '推广词',
                                           `keyword_type` int DEFAULT NULL COMMENT '关键字类型。0：未区分SEO、推广，1：自然优化，2：付费推广',
                                           `refer_page` text COMMENT '访客进入网站的来源页',
                                           `first_time` datetime DEFAULT NULL COMMENT '进入网站的时间',
                                           `first_page` text COMMENT '访客落地页面的URL',
                                           `first_page_title` varchar(100) DEFAULT NULL COMMENT '访客落地页面的标题',
                                           `first_page_alias` varchar(100) DEFAULT NULL COMMENT '访客落地页面的别名',
                                           `last_chat_time` datetime DEFAULT NULL COMMENT '上次对话的时间',
                                           `last_chat_staff_id` bigint DEFAULT NULL COMMENT '上次对话的客服ID。0：首次对话',
                                           `last_chat_staff_logname` varchar(100) DEFAULT NULL COMMENT '上次对话的客服账号',
                                           `last_chat_staff_name` varchar(100) DEFAULT NULL COMMENT '上次对话的客服姓名',
                                           `visit_page_count` int DEFAULT NULL COMMENT '访客本次会话浏览总页面数量',
                                           `visit_total_time` bigint DEFAULT NULL COMMENT '访客本次会话浏览总时长。单位：毫秒',
                                           `chat_record_id` varchar(100) DEFAULT NULL COMMENT '访客本次会话产生的人工对话记录ID、机器人对话记录ID、留言对话记录ID',
                                           `giveup_record_id` varchar(100) DEFAULT NULL COMMENT '访客本次会话点击对话，弹出信息收集框，放弃的记录ID',
                                           `visitor_out_time` datetime DEFAULT NULL COMMENT '访客离开时间',
                                           `route_id` bigint DEFAULT NULL COMMENT '接入对话的路由ID。-1：web访客的默认路由，-2：微信公众号对话的默认路由，-3：SDK对话的默认路由，-7：自定义渠道的默认路由',
                                           `route_name` varchar(100) DEFAULT NULL COMMENT '路由名称',
                                           `style_id` bigint DEFAULT NULL COMMENT '路由所使用的样式ID',
                                           `style_name` varchar(100) DEFAULT NULL COMMENT '路由所使用样式的名称',
                                           `chat_department_id` bigint DEFAULT NULL COMMENT '本次分配对话的接待组ID。0：全部人员可接待',
                                           `chat_department_name` varchar(100) DEFAULT NULL COMMENT '本地分配对话的接待组名称',
                                           `track_record_id` bigint DEFAULT NULL COMMENT '访客本次会话ID',
                                           `c1` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c2` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c3` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c4` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c5` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c6` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c7` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c8` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c9` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c10` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c11` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c12` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c13` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c14` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c15` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c16` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c17` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c18` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c19` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           `c20` varchar(100) DEFAULT NULL COMMENT '会员自定义字段',
                                           PRIMARY KEY (`id`),
                                           UNIQUE KEY `unique_keys_track_record_id` (`track_record_id`) USING BTREE,
                                           KEY `keyx_company_id` (`company_id`) USING BTREE,
                                           KEY `keyx_visitor_id` (`visitor_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='浏览数据';

-- 浏览轨迹
DROP TABLE IF EXISTS `bmp_server_track_record_page`;
CREATE TABLE `bmp_server_track_record_page` (
                                                `id` varchar(100) NOT NULL COMMENT '唯一ID',
                                                `create_date` datetime DEFAULT NULL COMMENT '创建时间',
                                                `create_by` varchar(100) DEFAULT NULL COMMENT '创建触发事件',
                                                `update_date` datetime DEFAULT NULL COMMENT '更新时间',
                                                `update_by` varchar(100) DEFAULT NULL COMMENT '更新触发事件',
                                                `disable` INT DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                                `del_flag` INT DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                                `company_id` varchar(100) NOT NULL COMMENT '公司ID',
                                                `visitor_id` varchar(100) DEFAULT NULL COMMENT '访客ID',
                                                `track_record_id` bigint DEFAULT NULL COMMENT '访客本次会话ID',
                                                `visit_time` datetime DEFAULT NULL COMMENT '访问时间',
                                                `page_url` text COMMENT '页面路径',
                                                `page_title` varchar(500) DEFAULT NULL COMMENT '页面标题',
                                                PRIMARY KEY (`id`),
                                                KEY `keyx_company_id` (`company_id`) USING BTREE,
                                                KEY `keyx_track_record_id` (`track_record_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='浏览轨迹';

-- 工单数据
DROP TABLE IF EXISTS `bmp_server_ticket_record`;
CREATE TABLE `bmp_server_ticket_record` (
                                            `id` varchar(100) NOT NULL COMMENT '唯一ID',
                                            `create_date` datetime DEFAULT NULL COMMENT '创建时间',
                                            `create_by` varchar(100) DEFAULT NULL COMMENT '创建触发事件',
                                            `update_date` datetime DEFAULT NULL COMMENT '更新时间',
                                            `update_by` varchar(100) DEFAULT NULL COMMENT '更新触发事件',
                                            `disable` INT DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                            `del_flag` INT DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                            `company_id` varchar(100) NOT NULL COMMENT '公司ID',
                                            `my_data` text COMMENT '开发者自定义扩展数据',
                                            `job_id` bigint NOT NULL COMMENT '工单ID',
                                            `job_Attribute` int NOT NULL COMMENT '工单属性。1：内部工单，2：外部工单',
                                            `visitor_enter_time` datetime DEFAULT NULL COMMENT '访客进入网站的时间',
                                            `visitor_media` int DEFAULT NULL COMMENT '访客端的媒介。1：电脑端网页，2：移动端网页，5：微信，6：Android SDK，9：自定义渠道，11：邮箱渠道',
                                            `visitor_type` int DEFAULT NULL COMMENT '访客类型。-1：未知，0：游客，1：会员，4：微信公众号渠道，5：自定义渠道，8：邮箱渠道',
                                            `media_id` varchar(100) DEFAULT NULL COMMENT '自定义渠道的渠道ID',
                                            `visitor_id` varchar(100) DEFAULT NULL COMMENT '访客ID',
                                            `visitor_name` varchar(100) DEFAULT NULL COMMENT '访客的姓名',
                                            `visitor_photo` varchar(500) DEFAULT NULL COMMENT '访客的头像地址',
                                            `visit_times` int DEFAULT NULL COMMENT '访客的来访次数',
                                            `visitor_lan` varchar(100) DEFAULT NULL COMMENT '访客的浏览器语言',
                                            `visitor_ip` varchar(100) DEFAULT NULL COMMENT '访客的来源IP',
                                            `visitor_country` varchar(100) DEFAULT NULL COMMENT '访客的来源国家',
                                            `visitor_province` varchar(100) DEFAULT NULL COMMENT '访客的来源省份',
                                            `visitor_city` varchar(100) DEFAULT NULL COMMENT '访客的来源城市',
                                            `browser_name` varchar(100) DEFAULT NULL COMMENT '访客的浏览器名称',
                                            `browser_version` varchar(100) DEFAULT NULL COMMENT '访客的浏览器版本号',
                                            `screen_resolution` varchar(100) DEFAULT NULL COMMENT '访客电脑的分辨率',
                                            `os_name` varchar(100) DEFAULT NULL COMMENT '访客电脑的操作系统',
                                            `os_version` varchar(100) DEFAULT NULL COMMENT '访客电脑的操作系统版本',
                                            `se` varchar(100) DEFAULT NULL COMMENT '访客来源的搜索引擎',
                                            `keyword` varchar(100) DEFAULT NULL COMMENT '访客来源的关键词',
                                            `bidding_word` varchar(100) DEFAULT NULL COMMENT '推广词',
                                            `keyword_type` int DEFAULT NULL COMMENT '关键字类型。0：未区分SEO、推广，1：自然优化，2：付费推广',
                                            `refer_page` text COMMENT '访客进入网站的来源页',
                                            `first_time` datetime DEFAULT NULL COMMENT '进入网站的时间',
                                            `first_page` text COMMENT '访客落地页面的URL',
                                            `first_page_title` varchar(100) DEFAULT NULL COMMENT '访客落地页面的标题',
                                            `first_page_alias` varchar(100) DEFAULT NULL COMMENT '访客落地页面的别名',
                                            `last_chat_time` datetime DEFAULT NULL COMMENT '上次对话的时间',
                                            `last_chat_staff_id` bigint DEFAULT NULL COMMENT '上次对话的客服ID.0：首次对话',
                                            `last_chat_staff_logname` varchar(100) DEFAULT NULL COMMENT '上次对话的客服账号',
                                            `last_chat_staff_name` varchar(100) DEFAULT NULL COMMENT '上次对话的客服姓名',
                                            `route_id` bigint DEFAULT NULL COMMENT '接入对话的路由ID。-1：web访客的默认路由，-2：微信公众号对话的默认路由，-3：SDK对话的默认路由，-7：自定义渠道的默认路由',
                                            `route_name` varchar(100) DEFAULT NULL COMMENT '路由名称',
                                            `route_style_id` bigint DEFAULT NULL COMMENT '路由所使用的样式ID',
                                            `style_name` varchar(100) DEFAULT NULL COMMENT '路由所使用样式的名称',
                                            `chat_department_id` bigint DEFAULT NULL COMMENT '本次分配对话的接待组ID。0：全部人员可接待',
                                            `chat_department_name` varchar(100) DEFAULT NULL COMMENT '本地分配对话的接待组名称',
                                            `title` varchar(100) DEFAULT NULL COMMENT '工单标题',
                                            `content` text COMMENT '工单内容',
                                            `job_topic` bigint DEFAULT NULL COMMENT '工单主题ID',
                                            `job_topic_name` varchar(100) DEFAULT NULL COMMENT '工单主题名称',
                                            `requester_lan` varchar(100) DEFAULT NULL COMMENT '请求者语言',
                                            `requester_user_id` varchar(100) DEFAULT NULL COMMENT '请求者ID',
                                            `requester_user_type` int DEFAULT NULL COMMENT '请求者类型。-1：客服，1：访客',
                                            `requester_user_name` varchar(100) DEFAULT NULL COMMENT '请求者姓名',
                                            `style_id` bigint DEFAULT NULL COMMENT '样式ID',
                                            `job_type` int DEFAULT NULL COMMENT '工单类型。1：问题，2：事务，3：故障，4：任务',
                                            `department_id` bigint DEFAULT NULL COMMENT '工单指派分组ID。0：客服创建时，选择处理人为“全部部门”',
                                            `department_name` varchar(100) DEFAULT NULL COMMENT '工单指派分组',
                                            `distribute_user_id` bigint DEFAULT NULL COMMENT '工单指派客服ID。0：由客服创建时，没有指定处理人；由访客创建时，工单自动分配为“手动分配”，即没有指定处理人',
                                            `distribute_user_name` varchar(100) DEFAULT NULL COMMENT '工单指派客服姓名',
                                            `distribute_user_role` varchar(100) DEFAULT NULL COMMENT '工单指派客服角色名',
                                            `distribute_user_logname` varchar(100) DEFAULT NULL COMMENT '工单指派客服账号',
                                            `updator_type` int DEFAULT NULL COMMENT '更新人类型。-1：客服，1：访客',
                                            `updator_id` varchar(100) DEFAULT NULL COMMENT '工单更新人ID',
                                            `updator_name` varchar(100) DEFAULT NULL COMMENT '工单更新人姓名',
                                            `job_follower_ids` varchar(100) DEFAULT NULL COMMENT '工单跟踪人ID',
                                            `job_follower_names` varchar(100) DEFAULT NULL COMMENT '工单跟踪人姓名',
                                            `priority` int DEFAULT NULL COMMENT '工单优先级。1：低，2：正常 ，3：高，4：紧急',
                                            `job_template_id` bigint DEFAULT NULL COMMENT '工单模版ID',
                                            `status` int DEFAULT NULL COMMENT '工单状态。1：新建，2：已开启，3：待回应，4：已挂起，5：已解决，6：已关闭',
                                            `reply_email` varchar(100) DEFAULT NULL COMMENT '工单回复邮箱',
                                            `reply_phone` varchar(100) DEFAULT NULL COMMENT '工单回复电话',
                                            `job_memo` varchar(100) DEFAULT NULL COMMENT '工单备注',
                                            `attachments` text COMMENT '工单附件信息，JSON字符串',
                                            `crm_id` bigint DEFAULT NULL COMMENT 'CRM字段-客户ID',
                                            `name` varchar(100) DEFAULT NULL COMMENT 'CRM字段-客户姓名',
                                            `category` varchar(100) DEFAULT NULL COMMENT 'CRM字段-客户类别',
                                            `nick_name` varchar(100) DEFAULT NULL COMMENT 'CRM字段-客户昵称',
                                            `gender` int DEFAULT NULL COMMENT 'CRM字段-客户性别。0：未知，1：男，2：女',
                                            `age` varchar(100) DEFAULT NULL COMMENT 'CRM字段-客户年龄',
                                            `birthday` varchar(100) DEFAULT NULL COMMENT 'CRM字段-客户生日',
                                            `marital_status` int DEFAULT NULL COMMENT 'CRM字段-客户婚姻状况。0：未知，1：未婚，2：已婚',
                                            `phone` varchar(100) DEFAULT NULL COMMENT 'CRM字段-客户电话',
                                            `qq` varchar(100) DEFAULT NULL COMMENT 'CRM字段-客户qq',
                                            `wechat` varchar(100) DEFAULT NULL COMMENT 'CRM字段-客户微信',
                                            `email` varchar(100) DEFAULT NULL COMMENT 'CRM字段-客户邮箱',
                                            `nation` varchar(100) DEFAULT NULL COMMENT 'CRM字段-客户所在国家',
                                            `province` varchar(100) DEFAULT NULL COMMENT 'CRM字段-客户所在省份',
                                            `city` varchar(100) DEFAULT NULL COMMENT 'CRM字段-客户所在城市',
                                            `address` varchar(500) DEFAULT NULL COMMENT 'CRM字段-客户地址',
                                            `photo` varchar(500) DEFAULT NULL COMMENT 'CRM字段-客户头像地址',
                                            `memo` varchar(100) DEFAULT NULL COMMENT 'CRM字段-备注',
                                            `c1` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c2` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c3` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c4` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c5` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c6` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c7` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c8` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c9` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c10` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c11` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c12` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c13` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c14` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c15` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c16` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c17` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c18` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c19` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `c20` varchar(100) DEFAULT NULL COMMENT 'CRM自定义字段',
                                            `t1` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t2` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t3` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t4` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t5` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t6` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t7` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t8` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t9` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t10` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t11` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t12` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t13` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t14` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t15` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t16` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t17` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t18` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t19` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `t20` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                            `evaluate_datetime` bigint DEFAULT NULL COMMENT '用户评价时间。时间戳格式',
                                            `main_item` int DEFAULT NULL COMMENT '评价满意度。1：非常差评，2：不满意 ，3：一般 ，4：满意 ，5：非常满意',
                                            `comment` varchar(100) DEFAULT NULL COMMENT '访客评价备注内容',
                                            `sub_items` varchar(100) DEFAULT NULL COMMENT '评价子项',
                                            PRIMARY KEY (`id`),
                                            UNIQUE KEY `unique_keys_job_id` (`job_id`) USING BTREE,
                                            KEY `keyx_company_id` (`company_id`) USING BTREE,
                                            KEY `keyx_visitor_id` (`visitor_id`) USING BTREE,
                                            KEY `keyx_distribute_user_id` (`distribute_user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='工单数据';

-- 工单更新内容
DROP TABLE IF EXISTS `bmp_server_ticket_record_content`;
CREATE TABLE `bmp_server_ticket_record_content` (
                                                    `id` varchar(100) NOT NULL COMMENT '唯一ID',
                                                    `create_date` datetime DEFAULT NULL COMMENT '创建时间',
                                                    `create_by` varchar(100) DEFAULT NULL COMMENT '创建触发事件',
                                                    `update_date` datetime DEFAULT NULL COMMENT '更新时间',
                                                    `update_by` varchar(100) DEFAULT NULL COMMENT '更新触发事件',
                                                    `disable` INT DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                                    `del_flag` INT DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                                    `company_id` varchar(100) NOT NULL COMMENT '公司ID',
                                                    `job_id` bigint DEFAULT NULL COMMENT '工单ID',
                                                    `job_Attribute` int DEFAULT NULL COMMENT '工单属性。1：内部工单，2：外部工单',
                                                    `status` int DEFAULT NULL COMMENT '工单状态。1：新建，2：已开启，3：待回应，4：已挂起，5：已解决，6：已关闭',
                                                    `reply_type` int DEFAULT NULL COMMENT '回复类型。1：内部回复，2：外部回复，3：内部回复和外部回复',
                                                    `priority` int DEFAULT NULL COMMENT '工单优先级。1：低，2：正常，3：高，4：紧急',
                                                    `job_type` int DEFAULT NULL COMMENT '工单类型。1：问题，2：事务，3：故障，4：任务',
                                                    `topic_id` bigint DEFAULT NULL COMMENT '工单主题ID',
                                                    `topic_name` varchar(100) DEFAULT NULL COMMENT '工单主题名称',
                                                    `distribute_staff_id` bigint DEFAULT NULL COMMENT '工单指派客服ID',
                                                    `distribute_staff_name` varchar(100) DEFAULT NULL COMMENT '工单指派客服姓名',
                                                    `distribute_staff_role` varchar(100) DEFAULT NULL COMMENT '工单指派客服角色名',
                                                    `distribute_staff_logname` varchar(100) DEFAULT NULL COMMENT '工单指派客服账号',
                                                    `updater_type` int DEFAULT NULL COMMENT '更新人类型。-1：客服，1：访客',
                                                    `updater_id` varchar(100) DEFAULT NULL COMMENT '客服ID或访客ID',
                                                    `updater_name` varchar(100) DEFAULT NULL COMMENT '客服姓名或访客姓名',
                                                    `reply_content` varchar(100) DEFAULT NULL COMMENT '回复内容',
                                                    `reply_email` varchar(100) DEFAULT NULL COMMENT '工单回复邮箱',
                                                    `reply_phone` varchar(100) DEFAULT NULL COMMENT '工单回复电话',
                                                    `t1` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t2` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t3` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t4` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t5` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t6` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t7` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t8` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t9` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t10` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t11` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t12` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t13` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t14` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t15` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t16` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t17` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t18` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t19` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    `t20` varchar(100) DEFAULT NULL COMMENT '工单自定义字段',
                                                    PRIMARY KEY (`id`),
                                                    KEY `keyx_company_id` (`company_id`) USING BTREE,
                                                    KEY `keyx_job_id` (`job_id`) USING BTREE,
                                                    KEY `keyx_updater_id` (`updater_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='工单更新内容';

-- 客户数据
DROP TABLE IF EXISTS `bmp_server_crm_data`;
CREATE TABLE `bmp_server_crm_data` (
                                       `id` varchar(100) NOT NULL COMMENT '唯一ID',
                                       `create_date` datetime DEFAULT NULL COMMENT '创建时间',
                                       `create_by` varchar(100) DEFAULT NULL COMMENT '创建触发事件',
                                       `update_date` datetime DEFAULT NULL COMMENT '更新时间',
                                       `update_by` varchar(100) DEFAULT NULL COMMENT '更新触发事件',
                                       `disable` INT DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                       `del_flag` INT DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                       `company_id` varchar(100) NOT NULL COMMENT '公司ID',
                                       `visitor_id` varchar(100) DEFAULT NULL COMMENT '访客ID',
                                       `crm_status` varchar(100) DEFAULT NULL COMMENT '客户信息状态。1：访客在信息收集窗口填写了数据，对话开始后自动触发，2：客服手动在一洽CRM系统填写了客户信息，3：客服分配客户',
                                       `create_staff_id` bigint DEFAULT NULL COMMENT '创建数据的客服ID"',
                                       `create_staff_logname` varchar(100) DEFAULT NULL COMMENT '创建数据的客服账号',
                                       `create_staff_name` varchar(100) DEFAULT NULL COMMENT '创建数据的客服姓名',
                                       `create_crm_date` datetime DEFAULT NULL COMMENT '创建数据的时间',
                                       `update_staff_id` bigint DEFAULT NULL COMMENT '修改数据的客服ID"',
                                       `update_staff_logname` varchar(100) DEFAULT NULL COMMENT '修改数据的客服账号',
                                       `update_staff_name` varchar(100) DEFAULT NULL COMMENT '修改数据的客服姓名',
                                       `update_crm_date` datetime DEFAULT NULL COMMENT '修改数据的时间',
                                       `distribute_staff_id` bigint DEFAULT NULL COMMENT '分配数据的客服ID"',
                                       `distribute_staff_logname` varchar(100) DEFAULT NULL COMMENT '分配数据的客服账号',
                                       `distribute_staff_name` varchar(100) DEFAULT NULL COMMENT '分配数据的客服姓名',
                                       `distribute_crm_date` datetime DEFAULT NULL COMMENT '分配数据的时间',
                                       `category` varchar(100) DEFAULT NULL COMMENT '客户类别',
                                       `name` varchar(100) DEFAULT NULL COMMENT '客户姓名',
                                       `nick_name` varchar(100) DEFAULT NULL COMMENT '客户昵称',
                                       `gender` int DEFAULT NULL COMMENT '客户性别。0：未知，1：男，2：女"',
                                       `age` varchar(100) DEFAULT NULL COMMENT '客户年龄',
                                       `birthday` varchar(100) DEFAULT NULL COMMENT '客户生日',
                                       `marital_status` int DEFAULT NULL COMMENT '婚姻状况。0：未知，1：未婚，2：已婚"',
                                       `phone` varchar(100) DEFAULT NULL COMMENT '客户电话',
                                       `qq` varchar(100) DEFAULT NULL COMMENT '客户qq',
                                       `wechat` varchar(100) DEFAULT NULL COMMENT '客户微信',
                                       `email` varchar(100) DEFAULT NULL COMMENT '客户邮箱',
                                       `nation` varchar(100) DEFAULT NULL COMMENT '客户所在国家',
                                       `province` varchar(100) DEFAULT NULL COMMENT '客户所在省份',
                                       `city` varchar(100) DEFAULT NULL COMMENT '客户所在城市',
                                       `address` varchar(500) DEFAULT NULL COMMENT '客户所在地址',
                                       `photo` varchar(500) DEFAULT NULL COMMENT '客户头像地址',
                                       `memo` varchar(100) DEFAULT NULL COMMENT '客户备注',
                                       `c1` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c2` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c3` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c4` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c5` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c6` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c7` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c8` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c9` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c10` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c11` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c12` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c13` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c14` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c15` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c16` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c17` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c18` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c19` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `c20` varchar(100) DEFAULT NULL COMMENT '自定义字段',
                                       `owner_id` bigint DEFAULT NULL COMMENT '数据所有者的客服ID',
                                       `owner_logname` varchar(100) DEFAULT NULL COMMENT '数据所有者的客服账号',
                                       `owner_name` varchar(100) DEFAULT NULL COMMENT '数据所有者的客服姓名',
                                       PRIMARY KEY (`id`),
                                       KEY `keyx_company_id` (`company_id`) USING BTREE,
                                       KEY `keyx_visitor_id` (`visitor_id`) USING BTREE,
                                       KEY `keyx_create_staff_id` (`create_staff_id`) USING BTREE,
                                       KEY `keyx_update_staff_id` (`update_staff_id`) USING BTREE,
                                       KEY `keyx_distribute_staff_id` (`distribute_staff_id`) USING BTREE,
                                       KEY `keyx_owner_id` (`owner_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='客户数据';

-- 一洽客服
DROP TABLE IF EXISTS `bmp_server_echat_staff`;
CREATE TABLE `bmp_server_echat_staff` (
                                          `id` varchar(100) NOT NULL COMMENT '唯一ID',
                                          `create_date` datetime DEFAULT NULL COMMENT '创建时间',
                                          `create_by` varchar(100) DEFAULT NULL COMMENT '创建触发事件',
                                          `update_date` datetime DEFAULT NULL COMMENT '更新时间',
                                          `update_by` varchar(100) DEFAULT NULL COMMENT '更新触发事件',
                                          `disable` INT DEFAULT '0' COMMENT '是否禁用。0：启用，1：禁用',
                                          `del_flag` INT DEFAULT '0' COMMENT '是否删除。0：未删，1：已删',
                                          `company_id` varchar(100) NOT NULL COMMENT '公司ID',
                                          `name` varchar(100) DEFAULT NULL COMMENT '客服姓名',
                                          `login_name` varchar(100) DEFAULT NULL COMMENT '客服账号',
                                          `nick_name` varchar(100) DEFAULT NULL COMMENT '客服昵称',
                                          `role` varchar(100) DEFAULT NULL COMMENT '客服角色',
                                          `mobile` varchar(100) DEFAULT NULL COMMENT '手机号码',
                                          `open_id` varchar(500) DEFAULT NULL COMMENT 'wechat openId',
                                          `email` varchar(500) DEFAULT NULL COMMENT '邮箱',
                                          PRIMARY KEY (`id`),
                                          KEY `keyx_company_id` (`company_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='一洽客服表';
